version: 0.0
os: linux
files:
  - source: /
    destination: /usr/myawsdemoapp
    overwrite: true
permissions:
  - object: /usr/myawsdemoapp/scripts
    pattern: "*.sh"
    owner: root
    group: root
    mode: 755
    type:
      - file
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 300
  ApplicationStop:
    - location: scripts/app_stop.sh
      timeout: 300

