version: 0.2

#env:
  #variables:
     # key: "value"
  #parameter-store:
     # key: "value"

phases:
  install:
    runtime-versions: 
      nodejs: 8
    commands:
      - npm install
      - npm install phantomjs
  pre_build:
    commands:
    - node -v
    - npm -v
    - aws --version
    - npm start
  build:
    commands:
    - echo Build started on `date`
    - npm test
  post_build:
    commands:
    - npm rebuild node-sass
    - npm run-script compile-sass
    - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
    # - location
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths

