version: 0.2

#env:
  #variables:
     # key: "value"
  #parameter-store:
     # key: "value"

phases:
  install:
    runtime-versions: 
      nodejs: 6
    commands:
      - npm install
      - npm install phantomjs
      - npm install -g pm2
      - pm2 update
  pre_build:
    commands:
    - node -v
    - npm -v
    - aws --version
    - npm rebuild node-sass
    - npm run-script compile-sass
  build:
    commands:
    - echo Build started on `date`
    - pm2 start bin/wwww -n www -f
    - npm test
    - pm2 stop www || true
  post_build:
    commands:
    - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
    # - location
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths

